# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e7f416963cd5fd45c0344d8e35182c9daf609ef7d2d8e91deed985e14826548f3bbe34c23cb415190f916631b0303f609f2f7ae2dd6a3dd640d7ce15857b410

test:
  secret_key_base: c3d6da7e78afd286cdb6f7d3d07828182db98a570efdb5726aa8686b6ec61fea0900e423be6395e8a0d5e9e09423b4b3bff1519271038facc057b641f13a58f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
